LittleQuest::Enemy Class Reference
#include <Enemy.h>
Public Member Functions
BP_OBJECT_TYPE (Enemy, Object)
bool Init () override
void Update () override
void LateDraw () override
void GUI () override
void OnHit (const ComponentCollision::HitInfo &hitInfo) override
virtual void GetHit (int damage)
float getDestroyTimer ()
Static Public Member Functions
static EnemyPtr Create (const float3 &pos, bool isPatrol=true, bool isBoss=false)
Protected Types
enum class EnemyState : unsigned int {
IDLE
, PATROL
, GIVE_UP
, WAIT
,
CHASING
, ATTACK
, GET_HIT
, DEAD
 }
Protected Member Functions
void ChangeState (EnemyState state)
virtual void Idle ()
virtual void Die ()
virtual void BackToInitialPosition (float3 &move)
virtual void Patrol (float3 &move)
virtual void Wait (float time)
virtual void Waiting (float deltaTime)
virtual bool FindPlayer ()
virtual void ChasePlayer (float3 &move)
virtual void Attack ()
Protected Attributes
EnemyState state
EnemyState prevState
EnemyState initialState
float3 spawnPos
float3 goal
bool isPatrol
std::vector< float3 > patrolPoint
int patrolIndex
float waitTime
bool isAttack = false
bool isHitPlayer
bool isFoundPlayer
float degree
const float speedBase = 0.3f
const float walkVal = 0.5f
const float runVal = 1.f
float speedFactor = 1.0f
bool isDead = false
float destroyTimer = 5
ObjectWeakPtr pPlayer
std::weak_ptr< ComponentModel > pModel
std::weak_ptr< ComponentHP > pHP
Detailed Description
Definition at line 12 of file Enemy.h.
Member Enumeration Documentation
EnemyState
enum class LittleQuest::Enemy::EnemyState : unsigned int [strong], [protected]
Enumerator
IDLE
PATROL
GIVE_UP
WAIT
CHASING
ATTACK
GET_HIT
DEAD
Definition at line 27 of file Enemy.h.
Member Function Documentation
Attack()
void LittleQuest::Enemy::Attack () [protected], [virtual]
Definition at line 224 of file Enemy.cpp.
References isHitPlayer, pModel, and Wait().
Referenced by Update().
BackToInitialPosition()
void LittleQuest::Enemy::BackToInitialPosition (float3 & move) [protected], [virtual]
Reimplemented in LittleQuest::Mutant.
Definition at line 139 of file Enemy.cpp.
References ChangeState(), initialState, runVal, spawnPos, and speedFactor.
Referenced by Update().
BP_OBJECT_TYPE()
LittleQuest::Enemy::BP_OBJECT_TYPE (Enemy , Object)
ChangeState()
void LittleQuest::Enemy::ChangeState (EnemyState state) [protected]
Definition at line 271 of file Enemy.cpp.
References prevState, and state.
Referenced by BackToInitialPosition(), ChasePlayer(), FindPlayer(), GetHit(), Idle(), Update(), Wait(), and Waiting().
ChasePlayer()
void LittleQuest::Enemy::ChasePlayer (float3 & move) [protected], [virtual]
Definition at line 199 of file Enemy.cpp.
References ATTACK, ChangeState(), pModel, pPlayer, runVal, and speedFactor.
Referenced by Update().
Create()
static EnemyPtr LittleQuest::Enemy::Create (const float3 & pos, bool isPatrol = true, bool isBoss = false) [static]
Die()
void LittleQuest::Enemy::Die () [protected], [virtual]
Reimplemented in LittleQuest::Mutant.
Definition at line 276 of file Enemy.cpp.
References isDead, and pModel.
Referenced by GetHit().
FindPlayer()
bool LittleQuest::Enemy::FindPlayer () [protected], [virtual]
Definition at line 128 of file Enemy.cpp.
References ChangeState(), CHASING, GIVE_UP, pPlayer, and prevState.
Referenced by Update().
getDestroyTimer()
float LittleQuest::Enemy::getDestroyTimer ()
Definition at line 282 of file Enemy.cpp.
References destroyTimer.
GetHit()
void LittleQuest::Enemy::GetHit (int damage) [virtual]
Reimplemented in LittleQuest::Mutant.
Definition at line 258 of file Enemy.cpp.
References ChangeState(), Die(), GET_HIT, pHP, and pModel.
GUI()
void LittleQuest::Enemy::GUI () [override]
Definition at line 111 of file Enemy.cpp.
Idle()
void LittleQuest::Enemy::Idle () [protected], [virtual]
Reimplemented in LittleQuest::Zombie.
Definition at line 119 of file Enemy.cpp.
References ChangeState(), and IDLE.
Referenced by Update().
Init()
bool LittleQuest::Enemy::Init () [override]
Definition at line 20 of file Enemy.cpp.
References goal, IDLE, initialState, isPatrol, PATROL, patrolIndex, patrolPoint, pPlayer, prevState, and state.
LateDraw()
void LittleQuest::Enemy::LateDraw () [override]
Definition at line 93 of file Enemy.cpp.
References destroyTimer, goal, isFoundPlayer, patrolIndex, pHP, pPlayer, and state.
OnHit()
void LittleQuest::Enemy::OnHit (const ComponentCollision::HitInfo & hitInfo) [override]
Definition at line 115 of file Enemy.cpp.
Patrol()
void LittleQuest::Enemy::Patrol (float3 & move) [protected], [virtual]
Reimplemented in LittleQuest::Mutant.
Definition at line 157 of file Enemy.cpp.
References goal, patrolIndex, patrolPoint, speedFactor, Wait(), and walkVal.
Referenced by Update().
Update()
void LittleQuest::Enemy::Update () [override]
Definition at line 41 of file Enemy.cpp.
References ATTACK, Attack(), BackToInitialPosition(), ChangeState(), ChasePlayer(), CHASING, destroyTimer, FindPlayer(), GET_HIT, GIVE_UP, IDLE, Idle(), isDead, PATROL, Patrol(), patrolPoint, pModel, speedBase, speedFactor, state, WAIT, and Waiting().
Wait()
void LittleQuest::Enemy::Wait (float time) [protected], [virtual]
Definition at line 183 of file Enemy.cpp.
References ChangeState(), pModel, WAIT, and waitTime.
Referenced by Attack(), and Patrol().
Waiting()
void LittleQuest::Enemy::Waiting (float deltaTime) [protected], [virtual]
Definition at line 189 of file Enemy.cpp.
References ChangeState(), IDLE, and waitTime.
Referenced by Update().
Member Data Documentation
degree
float LittleQuest::Enemy::degree [protected]
Definition at line 65 of file Enemy.h.
destroyTimer
float LittleQuest::Enemy::destroyTimer = 5 [protected]
Definition at line 73 of file Enemy.h.
Referenced by getDestroyTimer(), LateDraw(), and Update().
goal
float3 LittleQuest::Enemy::goal [protected]
Definition at line 56 of file Enemy.h.
Referenced by Init(), LateDraw(), and Patrol().
initialState
EnemyState LittleQuest::Enemy::initialState [protected]
Definition at line 39 of file Enemy.h.
Referenced by BackToInitialPosition(), and Init().
isAttack
bool LittleQuest::Enemy::isAttack = false [protected]
Definition at line 62 of file Enemy.h.
Referenced by LittleQuest::Mutant::OnHit().
isDead
bool LittleQuest::Enemy::isDead = false [protected]
Definition at line 72 of file Enemy.h.
Referenced by Die(), and Update().
isFoundPlayer
bool LittleQuest::Enemy::isFoundPlayer [protected]
Definition at line 64 of file Enemy.h.
Referenced by LateDraw().
isHitPlayer
bool LittleQuest::Enemy::isHitPlayer [protected]
Definition at line 63 of file Enemy.h.
Referenced by Attack(), and LittleQuest::Mutant::OnHit().
isPatrol
bool LittleQuest::Enemy::isPatrol [protected]
Definition at line 57 of file Enemy.h.
Referenced by LittleQuest::Mutant::Create(), and Init().
patrolIndex
int LittleQuest::Enemy::patrolIndex [protected]
Definition at line 59 of file Enemy.h.
Referenced by Init(), LateDraw(), and Patrol().
patrolPoint
std::vector<float3> LittleQuest::Enemy::patrolPoint [protected]
Definition at line 58 of file Enemy.h.
Referenced by Init(), Patrol(), and Update().
pHP
std::weak_ptr<ComponentHP> LittleQuest::Enemy::pHP [protected]
Definition at line 77 of file Enemy.h.
Referenced by GetHit(), LateDraw(), and LittleQuest::Mutant::LateDraw().
pModel
std::weak_ptr<ComponentModel> LittleQuest::Enemy::pModel [protected]
Definition at line 76 of file Enemy.h.
Referenced by Attack(), ChasePlayer(), Die(), GetHit(), LittleQuest::Mutant::Init(), LittleQuest::Mutant::OnHit(), Update(), and Wait().
pPlayer
ObjectWeakPtr LittleQuest::Enemy::pPlayer [protected]
Definition at line 75 of file Enemy.h.
Referenced by ChasePlayer(), FindPlayer(), Init(), and LateDraw().
prevState
EnemyState LittleQuest::Enemy::prevState [protected]
Definition at line 38 of file Enemy.h.
Referenced by ChangeState(), FindPlayer(), and Init().
runVal
const float LittleQuest::Enemy::runVal = 1.f [protected]
Definition at line 69 of file Enemy.h.
Referenced by BackToInitialPosition(), and ChasePlayer().
spawnPos
float3 LittleQuest::Enemy::spawnPos [protected]
Definition at line 55 of file Enemy.h.
Referenced by BackToInitialPosition().
speedBase
const float LittleQuest::Enemy::speedBase = 0.3f [protected]
Definition at line 67 of file Enemy.h.
Referenced by Update().
speedFactor
float LittleQuest::Enemy::speedFactor = 1.0f [protected]
Definition at line 70 of file Enemy.h.
Referenced by BackToInitialPosition(), ChasePlayer(), Patrol(), and Update().
state
EnemyState LittleQuest::Enemy::state [protected]
Definition at line 37 of file Enemy.h.
Referenced by ChangeState(), Init(), LateDraw(), and Update().
waitTime
float LittleQuest::Enemy::waitTime [protected]
Definition at line 60 of file Enemy.h.
Referenced by Wait(), and Waiting().
walkVal
const float LittleQuest::Enemy::walkVal = 0.5f [protected]
Definition at line 68 of file Enemy.h.
Referenced by Patrol().
The documentation for this class was generated from the following files:
Enemy.h
Enemy.cpp