LittleQuest::Boss Class Reference
ボスクラス
#include <Boss.h>
Public Member Functions
BP_OBJECT_TYPE (Boss, Object)
bool Init () override
初期化処理を行います。
void Update () override
更新処理を行います。
void LateDraw () override
遅い描画の処理を行います。
void GUI () override
ImGUIの処理を行います。
void OnHit (const ComponentCollision::HitInfo &hitInfo) override
当たりのコールバック
void Exit () override
終了処理を行います。
void GetHit (int damage)
攻撃される処理を行います。
void PlayTaunt ()
挑発動画を再生します。
void PlayDead ()
死亡動画を再生します。
bool IsPlayedTaunt ()
挑発動画が再生したのか。
bool IsDead ()
ボスが倒されたのか。
Static Public Member Functions
static BossPtr Create (const float3 &pos)
ボスを生成します。
Protected Types
enum BossState {
IDLE
, WAIT
, CHASE
, ATTACK
,
TURN_LEFT
, TURN_RIGHT
, GET_HIT
, ANGRY
,
TAUNT
, DEAD
 }
enum BossCombo {
SWIP
, COMBO5
, FAST_COMBO5
, BACKFLIP_PUNCH
,
BACKFLIP_CHARGE_PUNCH
, CHARGE_PUNCH
, ROAR_ATTACK
, NONE
 }
enum BossAnim {
SWIP_ATTACK
, QUICK_SWIP
, PUNCH
, QUICK_PUNCH
,
JUMP_ATTACK
, BACKFLIP
, DOUBLE_PUNCH
, CHARGE
,
ROAR
, TAUNT_ANIM
, ANGRY_AURA
 }
Protected Member Functions
void GameAction ()
void TransInAction ()
void TransOutAction ()
void Idle ()
void Wait ()
void ChasePlayer ()
void SelectAction ()
void SelectAngryAction ()
void Attack ()
void AttackAnimation (std::string animName, AnimInfo &animInfo, std::vector< ComponentCollisionCapsulePtr > atkCol={}, bool playSE=true)
void AttackAnimation (std::string animName, AnimInfo &animInfo, bool playSE)
void Combo5 ()
void BackflipPunch ()
void ChargePunch ()
void Swip ()
void PowerUp ()
void Taunt ()
void Damaging ()
void Die ()
void ChangeState (BossState state)
void SetAnimList ()
void SetComboList ()
Protected Attributes
const float WALK_SPEED = 0.5f
移動スピード
const float NORMAL_WAIT = 120.f
怒っていない時の待機時間
const float ANGRY_WAIT = 30.f
怒っている時の待機時間
const float TOO_CLOSE_DISTANCE = 15.0f
超近距離
const float CLOSE_DISTANCE = 30.0f
近距離
const float MIDDLE_DISTANCE = 60.0f
中距離
const float FAR_DISTANCE = 90.0
遠距離
const float FRONT_ANGLE = 60.0f
前の角度
const float BACK_ANGLE = 140.0f
背後の角度
const float DAMAGE_TIME = 420.0f
ダメージ溜まる時間
const int DAMAGE_CAP = int(MAX_HP * 0.15f)
ダメージ溜まるキャップ
const int MAX_HP = 500
最大HP
const int MAX_VOLUME = 255
BossState m_state = BossState::IDLE
BossCombo m_bossCombo = BossCombo::NONE
BossAnim m_anim = BossAnim::TAUNT_ANIM
ObjectWeakPtr m_pPlayer
std::weak_ptr< ComponentModel > m_pModel
std::weak_ptr< ComponentHP > m_pHP
std::weak_ptr< ComponentCollisionCapsule > m_pBodyBox
std::weak_ptr< ComponentCollisionCapsule > m_pLeftHandBox
std::weak_ptr< ComponentCollisionCapsule > m_pRightHandBox
std::weak_ptr< ComponentCollisionSphere > m_pAngryBox
std::unordered_map< std::string, AnimInfo > m_animList
std::unordered_map< BossCombo, float > m_comboList
Scene::SceneState m_sceneState = Scene::SceneState::GAME
float3 m_move = {0, 0, 0}
float m_waitFor = 0.0f
float m_waitTime = NORMAL_WAIT
float m_degree = 0.0f
float m_speedFactor = 1.0f
float m_destroyTimer = 5.0f
float m_currAnimTime = 0.0f
float m_damageTimer = 0
int m_combo = 0
int m_powerUpEffect = -1
int m_punchEffect = -1
int m_powerPunchEffect = -1
int m_doublePunchEffect = -1
int m_powerDoublePunchEffect = -1
int m_playingEffect = -1
int m_attackSE = -1
int m_damageCount = 0
int m_attackVal = 10
int * m_pEffectList
bool m_isHitPlayer = false
bool m_isDead = false
bool m_isAngry = false
bool m_playedSE = false
Detailed Description
ボスクラス
Definition at line 16 of file Boss.h.
Member Enumeration Documentation
BossAnim
enum LittleQuest::Boss::BossAnim [protected]
Enumerator
SWIP_ATTACK
QUICK_SWIP
PUNCH
QUICK_PUNCH
JUMP_ATTACK
BACKFLIP
DOUBLE_PUNCH
CHARGE
ROAR
TAUNT_ANIM
ANGRY_AURA
Definition at line 140 of file Boss.h.
BossCombo
enum LittleQuest::Boss::BossCombo [protected]
Enumerator
SWIP
COMBO5
FAST_COMBO5
BACKFLIP_PUNCH
BACKFLIP_CHARGE_PUNCH
CHARGE_PUNCH
ROAR_ATTACK
NONE
Definition at line 127 of file Boss.h.
BossState
enum LittleQuest::Boss::BossState [protected]
Enumerator
IDLE
WAIT
CHASE
ATTACK
TURN_LEFT
TURN_RIGHT
GET_HIT
ANGRY
TAUNT
DEAD
Definition at line 113 of file Boss.h.
Member Function Documentation
Attack()
void LittleQuest::Boss::Attack () [protected]
Definition at line 395 of file Boss.cpp.
References BACKFLIP_PUNCH, BackflipPunch(), CHARGE_PUNCH, ChargePunch(), COMBO5, Combo5(), m_bossCombo, SWIP, and Swip().
Referenced by GameAction().
AttackAnimation() [1/2]
void LittleQuest::Boss::AttackAnimation (std::string animName, AnimInfo & animInfo, bool playSE) [protected]
Definition at line 443 of file Boss.cpp.
References AttackAnimation().
AttackAnimation() [2/2]
void LittleQuest::Boss::AttackAnimation (std::string animName, AnimInfo & animInfo, std::vector< ComponentCollisionCapsulePtr > atkCol = {}, bool playSE = true) [protected]
Definition at line 412 of file Boss.cpp.
References m_attackSE, m_combo, m_currAnimTime, m_isHitPlayer, m_playedSE, m_pModel, and MAX_VOLUME.
Referenced by AttackAnimation(), BackflipPunch(), ChargePunch(), Combo5(), Damaging(), Swip(), and Taunt().
BackflipPunch()
void LittleQuest::Boss::BackflipPunch () [protected]
Definition at line 494 of file Boss.cpp.
References AttackAnimation(), BACKFLIP, ChangeState(), DOUBLE_PUNCH, m_animList, m_combo, m_currAnimTime, m_isAngry, m_pBodyBox, m_pEffectList, m_playingEffect, m_pLeftHandBox, m_pPlayer, m_pRightHandBox, m_waitFor, m_waitTime, STR, and WAIT.
Referenced by Attack().
BP_OBJECT_TYPE()
LittleQuest::Boss::BP_OBJECT_TYPE (Boss , Object)
ChangeState()
void LittleQuest::Boss::ChangeState (BossState state) [protected]
Definition at line 718 of file Boss.cpp.
References m_state.
Referenced by BackflipPunch(), ChargePunch(), ChasePlayer(), Combo5(), Damaging(), GameAction(), GetHit(), IsPlayedTaunt(), PlayDead(), PlayTaunt(), PowerUp(), SelectAction(), SelectAngryAction(), Swip(), Taunt(), and Wait().
ChargePunch()
void LittleQuest::Boss::ChargePunch () [protected]
Definition at line 532 of file Boss.cpp.
References AttackAnimation(), ChangeState(), CHARGE, DOUBLE_PUNCH, m_animList, m_combo, m_currAnimTime, m_isAngry, m_pEffectList, m_playingEffect, m_pLeftHandBox, m_pPlayer, m_pRightHandBox, m_waitFor, m_waitTime, STR, and WAIT.
Referenced by Attack().
ChasePlayer()
void LittleQuest::Boss::ChasePlayer () [protected]
Definition at line 242 of file Boss.cpp.
References ChangeState(), CLOSE_DISTANCE, IDLE, m_pModel, m_pPlayer, and WALK_SPEED.
Referenced by GameAction().
Combo5()
void LittleQuest::Boss::Combo5 () [protected]
Definition at line 447 of file Boss.cpp.
References AttackAnimation(), ChangeState(), m_animList, m_combo, m_currAnimTime, m_isAngry, m_pEffectList, m_playingEffect, m_pLeftHandBox, m_pPlayer, m_pRightHandBox, m_waitFor, m_waitTime, PUNCH, QUICK_PUNCH, QUICK_SWIP, STR, SWIP_ATTACK, and WAIT.
Referenced by Attack().
Create()
BossPtr LittleQuest::Boss::Create (const float3 & pos) [static]
ボスを生成します。
Definition at line 20 of file Boss.cpp.
Referenced by LittleQuest::Stage01::Init().
Damaging()
void LittleQuest::Boss::Damaging () [protected]
Definition at line 672 of file Boss.cpp.
References AttackAnimation(), ChangeState(), GET_HIT, m_animList, m_combo, m_waitFor, m_waitTime, STR, and WAIT.
Referenced by GameAction().
Die()
void LittleQuest::Boss::Die () [protected]
Definition at line 684 of file Boss.cpp.
References DEAD, m_pAngryBox, m_pBodyBox, m_pModel, and STR.
Referenced by GameAction(), and TransOutAction().
Exit()
void LittleQuest::Boss::Exit () [override]
終了処理を行います。
Definition at line 727 of file Boss.cpp.
References m_attackSE, m_doublePunchEffect, m_pEffectList, m_powerDoublePunchEffect, m_powerPunchEffect, m_powerUpEffect, and m_punchEffect.
GameAction()
void LittleQuest::Boss::GameAction () [protected]
Definition at line 126 of file Boss.cpp.
References ANGRY, ATTACK, Attack(), ChangeState(), CHASE, ChasePlayer(), Damaging(), DEAD, Die(), GET_HIT, IDLE, Idle(), m_bossCombo, m_damageCount, m_damageTimer, m_isAngry, m_pHP, m_pModel, m_pPlayer, m_state, NONE, PowerUp(), SelectAction(), SelectAngryAction(), STR, TURN_LEFT, TURN_RIGHT, WAIT, and Wait().
Referenced by Update().
GetHit()
void LittleQuest::Boss::GetHit (int damage)
攻撃される処理を行います。
Parameters
damage 受けるダメージ
Definition at line 649 of file Boss.cpp.
References ANGRY, ChangeState(), DAMAGE_CAP, DAMAGE_TIME, DEAD, GET_HIT, m_bossCombo, m_combo, m_damageCount, m_damageTimer, m_pHP, m_state, and NONE.
Referenced by LittleQuest::Player::OnHit().
GUI()
void LittleQuest::Boss::GUI () [override]
ImGUIの処理を行います。
Definition at line 209 of file Boss.cpp.
Idle()
void LittleQuest::Boss::Idle () [protected]
Definition at line 227 of file Boss.cpp.
References IDLE, m_pModel, and STR.
Referenced by GameAction(), and TransOutAction().
Init()
bool LittleQuest::Boss::Init () [override]
初期化処理を行います。
Returns
初期化できたかどうか
Definition at line 29 of file Boss.cpp.
References BACKFLIP, LittleQuest::ComponentHP::BOSS, CHARGE, DEAD, DOUBLE_PUNCH, GET_HIT, IDLE, JUMP_ATTACK, m_attackSE, m_bossCombo, m_doublePunchEffect, m_pBodyBox, m_pEffectList, m_pHP, m_pLeftHandBox, m_pModel, m_powerDoublePunchEffect, m_powerPunchEffect, m_powerUpEffect, m_pPlayer, m_pRightHandBox, m_punchEffect, m_state, MAX_HP, NONE, PUNCH, ROAR, SetAnimList(), SetComboList(), STR, SWIP_ATTACK, TAUNT_ANIM, TURN_LEFT, and TURN_RIGHT.
IsDead()
bool LittleQuest::Boss::IsDead ()
ボスが倒されたのか。
Return values
true 倒された
false 倒されていない
Definition at line 714 of file Boss.cpp.
References m_pHP.
IsPlayedTaunt()
bool LittleQuest::Boss::IsPlayedTaunt ()
挑発動画が再生したのか。
Return values
true 再生した
false 再生していない
Definition at line 706 of file Boss.cpp.
References ChangeState(), m_pModel, STR, TAUNT_ANIM, and WAIT.
LateDraw()
void LittleQuest::Boss::LateDraw () [override]
遅い描画の処理を行います。
Definition at line 196 of file Boss.cpp.
References m_pHP, and m_sceneState.
OnHit()
void LittleQuest::Boss::OnHit (const ComponentCollision::HitInfo & hitInfo) [override]
当たりのコールバック
Parameters
hitInfo　当たったコリジョンのヒット情報
Definition at line 213 of file Boss.cpp.
References m_attackVal, m_bossCombo, m_comboList, m_isAngry, and m_isHitPlayer.
PlayDead()
void LittleQuest::Boss::PlayDead ()
死亡動画を再生します。
Definition at line 702 of file Boss.cpp.
References ChangeState(), and DEAD.
PlayTaunt()
void LittleQuest::Boss::PlayTaunt ()
挑発動画を再生します。
Definition at line 697 of file Boss.cpp.
References ChangeState(), m_combo, and TAUNT.
PowerUp()
void LittleQuest::Boss::PowerUp () [protected]
Definition at line 609 of file Boss.cpp.
References ANGRY_AURA, ANGRY_WAIT, ChangeState(), CHARGE, m_animList, m_combo, m_currAnimTime, m_isAngry, m_isHitPlayer, m_pAngryBox, m_playingEffect, m_pModel, m_powerUpEffect, m_waitFor, m_waitTime, STR, and WAIT.
Referenced by GameAction().
SelectAction()
void LittleQuest::Boss::SelectAction () [protected]
Definition at line 260 of file Boss.cpp.
References ATTACK, BACK_ANGLE, BACKFLIP_PUNCH, ChangeState(), CHARGE_PUNCH, CHASE, CLOSE_DISTANCE, COMBO5, FAR_DISTANCE, FRONT_ANGLE, m_bossCombo, m_combo, m_pPlayer, SWIP, TOO_CLOSE_DISTANCE, TURN_LEFT, and TURN_RIGHT.
Referenced by GameAction().
SelectAngryAction()
void LittleQuest::Boss::SelectAngryAction () [protected]
Definition at line 329 of file Boss.cpp.
References ATTACK, BACK_ANGLE, BACKFLIP_PUNCH, ChangeState(), CHARGE_PUNCH, CHASE, CLOSE_DISTANCE, COMBO5, FAR_DISTANCE, FRONT_ANGLE, m_bossCombo, m_combo, m_pPlayer, SWIP, TOO_CLOSE_DISTANCE, TURN_LEFT, and TURN_RIGHT.
Referenced by GameAction().
SetAnimList()
void LittleQuest::Boss::SetAnimList () [protected]
Definition at line 738 of file Boss.cpp.
References ANGRY_AURA, BACKFLIP, CHARGE, DOUBLE_PUNCH, GET_HIT, m_animList, PUNCH, QUICK_PUNCH, QUICK_SWIP, ROAR, STR, SWIP_ATTACK, and TAUNT_ANIM.
Referenced by Init().
SetComboList()
void LittleQuest::Boss::SetComboList () [protected]
Definition at line 823 of file Boss.cpp.
References BACKFLIP_PUNCH, CHARGE_PUNCH, COMBO5, m_comboList, and SWIP.
Referenced by Init().
Swip()
void LittleQuest::Boss::Swip () [protected]
Definition at line 563 of file Boss.cpp.
References AttackAnimation(), ChangeState(), m_animList, m_combo, m_currAnimTime, m_isAngry, m_pEffectList, m_playingEffect, m_pLeftHandBox, m_pPlayer, m_pRightHandBox, m_waitFor, m_waitTime, PUNCH, STR, SWIP_ATTACK, and WAIT.
Referenced by Attack().
Taunt()
void LittleQuest::Boss::Taunt () [protected]
Definition at line 598 of file Boss.cpp.
References AttackAnimation(), ChangeState(), IDLE, m_animList, m_combo, STR, and TAUNT_ANIM.
Referenced by TransInAction().
TransInAction()
void LittleQuest::Boss::TransInAction () [protected]
Definition at line 115 of file Boss.cpp.
References IDLE, m_pModel, m_state, STR, TAUNT, and Taunt().
Referenced by Update().
TransOutAction()
void LittleQuest::Boss::TransOutAction () [protected]
Definition at line 185 of file Boss.cpp.
References DEAD, Die(), Idle(), and m_state.
Referenced by Update().
Update()
void LittleQuest::Boss::Update () [override]
更新処理を行います。
Definition at line 101 of file Boss.cpp.
References GameAction(), m_sceneState, TransInAction(), and TransOutAction().
Wait()
void LittleQuest::Boss::Wait () [protected]
Definition at line 231 of file Boss.cpp.
References ChangeState(), IDLE, m_bossCombo, m_combo, m_isAngry, m_pHP, m_pModel, m_waitFor, NONE, and STR.
Referenced by GameAction().
Member Data Documentation
ANGRY_WAIT
const float LittleQuest::Boss::ANGRY_WAIT = 30.f [protected]
怒っている時の待機時間
Definition at line 92 of file Boss.h.
Referenced by PowerUp().
BACK_ANGLE
const float LittleQuest::Boss::BACK_ANGLE = 140.0f [protected]
背後の角度
Definition at line 104 of file Boss.h.
Referenced by SelectAction(), and SelectAngryAction().
CLOSE_DISTANCE
const float LittleQuest::Boss::CLOSE_DISTANCE = 30.0f [protected]
近距離
Definition at line 96 of file Boss.h.
Referenced by ChasePlayer(), SelectAction(), and SelectAngryAction().
DAMAGE_CAP
const int LittleQuest::Boss::DAMAGE_CAP = int(MAX_HP * 0.15f) [protected]
ダメージ溜まるキャップ
Definition at line 108 of file Boss.h.
Referenced by GetHit().
DAMAGE_TIME
const float LittleQuest::Boss::DAMAGE_TIME = 420.0f [protected]
ダメージ溜まる時間
Definition at line 106 of file Boss.h.
Referenced by GetHit().
FAR_DISTANCE
const float LittleQuest::Boss::FAR_DISTANCE = 90.0 [protected]
遠距離
Definition at line 100 of file Boss.h.
Referenced by SelectAction(), and SelectAngryAction().
FRONT_ANGLE
const float LittleQuest::Boss::FRONT_ANGLE = 60.0f [protected]
前の角度
Definition at line 102 of file Boss.h.
Referenced by SelectAction(), and SelectAngryAction().
m_anim
BossAnim LittleQuest::Boss::m_anim = BossAnim::TAUNT_ANIM [protected]
Definition at line 153 of file Boss.h.
m_animList
std::unordered_map<std::string, AnimInfo> LittleQuest::Boss::m_animList [protected]
Definition at line 162 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Damaging(), PowerUp(), SetAnimList(), Swip(), and Taunt().
m_attackSE
int LittleQuest::Boss::m_attackSE = -1 [protected]
Definition at line 182 of file Boss.h.
Referenced by AttackAnimation(), Exit(), and Init().
m_attackVal
int LittleQuest::Boss::m_attackVal = 10 [protected]
Definition at line 184 of file Boss.h.
Referenced by OnHit().
m_bossCombo
BossCombo LittleQuest::Boss::m_bossCombo = BossCombo::NONE [protected]
Definition at line 138 of file Boss.h.
Referenced by Attack(), GameAction(), GetHit(), Init(), OnHit(), SelectAction(), SelectAngryAction(), and Wait().
m_combo
int LittleQuest::Boss::m_combo = 0 [protected]
Definition at line 175 of file Boss.h.
Referenced by AttackAnimation(), BackflipPunch(), ChargePunch(), Combo5(), Damaging(), GetHit(), PlayTaunt(), PowerUp(), SelectAction(), SelectAngryAction(), Swip(), Taunt(), and Wait().
m_comboList
std::unordered_map<BossCombo, float> LittleQuest::Boss::m_comboList [protected]
Definition at line 163 of file Boss.h.
Referenced by OnHit(), and SetComboList().
m_currAnimTime
float LittleQuest::Boss::m_currAnimTime = 0.0f [protected]
Definition at line 173 of file Boss.h.
Referenced by AttackAnimation(), BackflipPunch(), ChargePunch(), Combo5(), PowerUp(), and Swip().
m_damageCount
int LittleQuest::Boss::m_damageCount = 0 [protected]
Definition at line 183 of file Boss.h.
Referenced by GameAction(), and GetHit().
m_damageTimer
float LittleQuest::Boss::m_damageTimer = 0 [protected]
Definition at line 174 of file Boss.h.
Referenced by GameAction(), and GetHit().
m_degree
float LittleQuest::Boss::m_degree = 0.0f [protected]
Definition at line 170 of file Boss.h.
m_destroyTimer
float LittleQuest::Boss::m_destroyTimer = 5.0f [protected]
Definition at line 172 of file Boss.h.
m_doublePunchEffect
int LittleQuest::Boss::m_doublePunchEffect = -1 [protected]
Definition at line 179 of file Boss.h.
Referenced by Exit(), and Init().
m_isAngry
bool LittleQuest::Boss::m_isAngry = false [protected]
Definition at line 188 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), GameAction(), OnHit(), PowerUp(), Swip(), and Wait().
m_isDead
bool LittleQuest::Boss::m_isDead = false [protected]
Definition at line 187 of file Boss.h.
m_isHitPlayer
bool LittleQuest::Boss::m_isHitPlayer = false [protected]
Definition at line 186 of file Boss.h.
Referenced by AttackAnimation(), OnHit(), and PowerUp().
m_move
float3 LittleQuest::Boss::m_move = {0, 0, 0} [protected]
Definition at line 167 of file Boss.h.
m_pAngryBox
std::weak_ptr<ComponentCollisionSphere> LittleQuest::Boss::m_pAngryBox [protected]
Definition at line 161 of file Boss.h.
Referenced by Die(), and PowerUp().
m_pBodyBox
std::weak_ptr<ComponentCollisionCapsule> LittleQuest::Boss::m_pBodyBox [protected]
Definition at line 158 of file Boss.h.
Referenced by BackflipPunch(), Die(), and Init().
m_pEffectList
int* LittleQuest::Boss::m_pEffectList [protected]
Definition at line 185 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Exit(), Init(), and Swip().
m_pHP
std::weak_ptr<ComponentHP> LittleQuest::Boss::m_pHP [protected]
Definition at line 157 of file Boss.h.
Referenced by GameAction(), GetHit(), Init(), IsDead(), LateDraw(), and Wait().
m_playedSE
bool LittleQuest::Boss::m_playedSE = false [protected]
Definition at line 189 of file Boss.h.
Referenced by AttackAnimation().
m_playingEffect
int LittleQuest::Boss::m_playingEffect = -1 [protected]
Definition at line 181 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), PowerUp(), and Swip().
m_pLeftHandBox
std::weak_ptr<ComponentCollisionCapsule> LittleQuest::Boss::m_pLeftHandBox [protected]
Definition at line 159 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Init(), and Swip().
m_pModel
std::weak_ptr<ComponentModel> LittleQuest::Boss::m_pModel [protected]
Definition at line 156 of file Boss.h.
Referenced by AttackAnimation(), ChasePlayer(), Die(), GameAction(), Idle(), Init(), IsPlayedTaunt(), PowerUp(), TransInAction(), and Wait().
m_powerDoublePunchEffect
int LittleQuest::Boss::m_powerDoublePunchEffect = -1 [protected]
Definition at line 180 of file Boss.h.
Referenced by Exit(), and Init().
m_powerPunchEffect
int LittleQuest::Boss::m_powerPunchEffect = -1 [protected]
Definition at line 178 of file Boss.h.
Referenced by Exit(), and Init().
m_powerUpEffect
int LittleQuest::Boss::m_powerUpEffect = -1 [protected]
Definition at line 176 of file Boss.h.
Referenced by Exit(), Init(), and PowerUp().
m_pPlayer
ObjectWeakPtr LittleQuest::Boss::m_pPlayer [protected]
Definition at line 155 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), ChasePlayer(), Combo5(), GameAction(), Init(), SelectAction(), SelectAngryAction(), and Swip().
m_pRightHandBox
std::weak_ptr<ComponentCollisionCapsule> LittleQuest::Boss::m_pRightHandBox [protected]
Definition at line 160 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Init(), and Swip().
m_punchEffect
int LittleQuest::Boss::m_punchEffect = -1 [protected]
Definition at line 177 of file Boss.h.
Referenced by Exit(), and Init().
m_sceneState
Scene::SceneState LittleQuest::Boss::m_sceneState = Scene::SceneState::GAME [protected]
Definition at line 165 of file Boss.h.
Referenced by LateDraw(), and Update().
m_speedFactor
float LittleQuest::Boss::m_speedFactor = 1.0f [protected]
Definition at line 171 of file Boss.h.
m_state
BossState LittleQuest::Boss::m_state = BossState::IDLE [protected]
Definition at line 125 of file Boss.h.
Referenced by ChangeState(), GameAction(), GetHit(), Init(), TransInAction(), and TransOutAction().
m_waitFor
float LittleQuest::Boss::m_waitFor = 0.0f [protected]
Definition at line 168 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Damaging(), PowerUp(), Swip(), and Wait().
m_waitTime
float LittleQuest::Boss::m_waitTime = NORMAL_WAIT [protected]
Definition at line 169 of file Boss.h.
Referenced by BackflipPunch(), ChargePunch(), Combo5(), Damaging(), PowerUp(), and Swip().
MAX_HP
const int LittleQuest::Boss::MAX_HP = 500 [protected]
最大HP
Definition at line 110 of file Boss.h.
Referenced by Init().
MAX_VOLUME
const int LittleQuest::Boss::MAX_VOLUME = 255 [protected]
Definition at line 111 of file Boss.h.
Referenced by AttackAnimation().
MIDDLE_DISTANCE
const float LittleQuest::Boss::MIDDLE_DISTANCE = 60.0f [protected]
中距離
Definition at line 98 of file Boss.h.
NORMAL_WAIT
const float LittleQuest::Boss::NORMAL_WAIT = 120.f [protected]
怒っていない時の待機時間
Definition at line 90 of file Boss.h.
TOO_CLOSE_DISTANCE
const float LittleQuest::Boss::TOO_CLOSE_DISTANCE = 15.0f [protected]
超近距離
Definition at line 94 of file Boss.h.
Referenced by SelectAction(), and SelectAngryAction().
WALK_SPEED
const float LittleQuest::Boss::WALK_SPEED = 0.5f [protected]
移動スピード
Definition at line 88 of file Boss.h.
Referenced by ChasePlayer().
The documentation for this class was generated from the following files:
Boss.h
Boss.cpp